import React from 'react';
import { Button } from '../components/Button';
import { Sparkles, Users, Heart } from 'lucide-react';

interface HomeScreenProps {
  onStart: () => void;
  onLogin: () => void;
  hasAccount: boolean;
}

export const HomeScreen: React.FC<HomeScreenProps> = ({ onStart, onLogin, hasAccount }) => {
  return (
    <div className="flex flex-col items-center justify-center flex-1 text-center space-y-8 animate-fade-in">
      <div className="space-y-4 max-w-2xl">
        <h1 className="text-6xl md:text-8xl font-black tracking-tighter">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400">
            TRUTH
          </span>
          <br />
          <span className="text-white text-4xl md:text-6xl">OR</span>
          <br />
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-400 via-red-400 to-orange-400">
            DARE
          </span>
        </h1>
        <p className="text-gray-400 text-xl md:text-2xl font-light">
          The AI-powered party game that adapts to your vibe.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-4xl mt-12">
        <div className="p-6 bg-white/5 rounded-2xl border border-white/10 backdrop-blur-sm">
          <Users className="w-10 h-10 text-blue-400 mx-auto mb-4" />
          <h3 className="text-xl font-bold mb-2">For Friends</h3>
          <p className="text-gray-400 text-sm">Hilarious challenges to break the ice and bond.</p>
        </div>
        <div className="p-6 bg-white/5 rounded-2xl border border-white/10 backdrop-blur-sm">
          <Heart className="w-10 h-10 text-pink-400 mx-auto mb-4" />
          <h3 className="text-xl font-bold mb-2">For Couples</h3>
          <p className="text-gray-400 text-sm">Deep questions and spicy dares to heat things up.</p>
        </div>
        <div className="p-6 bg-white/5 rounded-2xl border border-white/10 backdrop-blur-sm">
          <Sparkles className="w-10 h-10 text-yellow-400 mx-auto mb-4" />
          <h3 className="text-xl font-bold mb-2">AI Powered</h3>
          <p className="text-gray-400 text-sm">Infinite unique cards generated by Gemini.</p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 mt-12 w-full max-w-md">
        <Button onClick={onStart} size="lg" className="w-full flex-1">
          Start New Game
        </Button>
        <Button onClick={onLogin} variant="secondary" size="lg" className="w-full flex-1">
          {hasAccount ? 'My Profile' : 'Create Account'}
        </Button>
      </div>
    </div>
  );
};